SIE\CoreBundle\Entity\AdresseIpEquipement:
    type: entity
    table: ADRESSE_IP_EQUIPEMENT
    id:
        idAdresseIpEquipement:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_adresse_ip_equipement
            generator:
                strategy: IDENTITY
    fields:
        adresseIpEquipement:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: adresse_ip_equipement
    lifecycleCallbacks: {  }
