SIE\CoreBundle\Entity\ChargeExploitation:
    type: entity
    table: CHARGE_EXPLOITATION
    id:
        idCex:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_cex
            generator:
                strategy: IDENTITY
    fields:
        triCex:
            type: string
            nullable: true
            length: 3
            options:
                fixed: false
            column: tri_cex
    lifecycleCallbacks: {  }
