SIE\CoreBundle\Entity\Config:
    type: entity
    table: CONFIG
    id:
        idConfig:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_config
            generator:
                strategy: IDENTITY
    fields:
        lienConfig:
            type: string
            nullable: true
            length: 90
            options:
                fixed: false
            column: lien_config
        libConfig:
            type: string
            nullable: true
            length: 75
            options:
                fixed: false
            column: lib_config
    lifecycleCallbacks: {  }
