SIE\CoreBundle\Entity\CorrespondanceEquipementAdresseIp:
    type: entity
    table: CORRESPONDANCE_EQUIPEMENT_ADRESSE_IP
    indexes:
        FK_corresp_equip_adress_ip1:
            columns:
                - id_adresse_ip_fk_ceap
        IDX_FE7DAFA96EB983A2:
            columns:
                - id_equipement_fk_ceap
    uniqueConstraints:
        id_equipement_fk_ceap:
            columns:
                - id_equipement_fk_ceap
                - id_adresse_ip_fk_ceap
    id:
        idEquipementAdresseIp:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_equipement_adresse_ip
            generator:
                strategy: IDENTITY
    fields:
        infoCom:
            type: string
            nullable: true
            length: 25
            options:
                fixed: false
            column: info_com
    manyToOne:
        idAdresseIpFkCeap:
            targetEntity: AdresseIpEquipement
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_adresse_ip_fk_ceap:
                    referencedColumnName: id_adresse_ip_equipement
            orphanRemoval: false
        idEquipementFkCeap:
            targetEntity: Equipement
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_equipement_fk_ceap:
                    referencedColumnName: id_equipement
            orphanRemoval: false
    lifecycleCallbacks: {  }
