SIE\CoreBundle\Entity\SocieteCentral:
    type: entity
    table: SOCIETE_CENTRAL
    indexes:
        FK_central_societe1:
            columns:
                - id_central
        IDX_8D9E89D5C7F894CD:
            columns:
                - id_societe
    uniqueConstraints:
        id_societe:
            columns:
                - id_societe
                - id_central
    id:
        idSocieteCentral:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_societe_central
            generator:
                strategy: IDENTITY
    manyToOne:
        idCentral:
            targetEntity: Central
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_central:
                    referencedColumnName: id_central
            orphanRemoval: false
        idSociete:
            targetEntity: Societe
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_societe:
                    referencedColumnName: id_societe
            orphanRemoval: false
    lifecycleCallbacks: {  }
