SIE\CoreBundle\Entity\Societe:
    type: entity
    table: SOCIETE
    id:
        idSociete:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_societe
            generator:
                strategy: IDENTITY
    fields:
        libSociete:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: lib_societe
    lifecycleCallbacks: {  }
