SIE\CoreBundle\Entity\TypeConnectionEquipement:
    type: entity
    table: TYPE_CONNECTION_EQUIPEMENT
    id:
        idTypeConnection:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_type_connection
            generator:
                strategy: IDENTITY
    fields:
        libTypeConnection:
            type: string
            nullable: true
            length: 25
            options:
                fixed: false
            column: lib_type_connection
    lifecycleCallbacks: {  }
