SIE\CoreBundle\Entity\TypeCentral:
    type: entity
    table: TYPE_CENTRAL
    id:
        idTypeCentral:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_type_central
            generator:
                strategy: IDENTITY
    fields:
        libTypeCentral:
            type: string
            nullable: true
            length: 25
            options:
                fixed: false
            column: lib_type_central
    lifecycleCallbacks: {  }
