SIE\CoreBundle\Entity\Vue:
    type: entity
    table: VUE
    indexes:
        FK_vue_central:
            columns:
                - id_central
    id:
        idVue:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_vue
            generator:
                strategy: IDENTITY
    fields:
        lienVue:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: lien_vue
    manyToOne:
        idCentral:
            targetEntity: Central
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_central:
                    referencedColumnName: id_central
            orphanRemoval: false
    lifecycleCallbacks: {  }
