SIE\CoreBundle\Entity\Societe:
    type: entity
    table: SOCIETE
    id:
        idSociete:
            id: true
            type: integer
            column: id_societe
            generator:
                strategy: IDENTITY
    fields:
        libSociete:
            type: string
            length: 50
            nullable: true
            options:
                fixed: ''
            column: lib_societe
    lifecycleCallbacks: {  }
