SIE\CoreBundle\Entity\AdresseMacEquipement:
    type: entity
    table: ADRESSE_MAC_EQUIPEMENT
    id:
        idAdresseMacEquipement:
            id: true
            type: integer
            column: id_adresse_mac_equipement
            generator:
                strategy: IDENTITY
    fields:
        adresseMacEquipement:
            type: string
            length: 50
            nullable: true
            options:
                fixed: ''
            column: adresse_mac_equipement
    lifecycleCallbacks: {  }
