SIE\CoreBundle\Entity\TypeCentral:
    type: entity
    table: TYPE_CENTRAL
    id:
        idTypeCentral:
            id: true
            type: integer
            column: id_type_central
            generator:
                strategy: IDENTITY
    fields:
        libTypeCentral:
            type: string
            length: 25
            nullable: true
            options:
                fixed: ''
            column: lib_type_central
    lifecycleCallbacks: {  }
