SIE\CoreBundle\Entity\Protocol:
    type: entity
    table: PROTOCOL
    id:
        idProtocol:
            id: true
            type: integer
            column: id_protocol
            generator:
                strategy: IDENTITY
    fields:
        libProtocol:
            type: string
            length: 15
            nullable: true
            options:
                fixed: ''
            column: lib_protocol
    lifecycleCallbacks: {  }
