SIE\CoreBundle\Entity\Central:
    type: entity
    table: CENTRAL
    indexes:
        FK_central_dr:
            columns:
                - id_direction
        FK_type_central:
            columns:
                - id_type_central
        FK_central_cex:
            columns:
                - id_cex
    id:
        idCentral:
            id: true
            type: integer
            column: id_central
            generator:
                strategy: IDENTITY
    fields:
        libCentral:
            type: string
            length: 35
            nullable: true
            options:
                fixed: ''
            column: lib_central
        etendueCentral:
            type: integer
            nullable: true
            options:
                unsigned: ''
            column: etendue_central
        codeAnalytique:
            type: string
            length: 35
            nullable: true
            options:
                fixed: ''
            column: code_analytique
        societe:
            type: string
            length: 30
            nullable: true
            options:
                fixed: ''
    manyToOne:
        idCex:
            targetEntity: SIE\CoreBundle\Entity\ChargeExploitation
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_cex:
                    referencedColumnName: id_cex
            orphanRemoval: false
        idTypeCentral:
            targetEntity: SIE\CoreBundle\Entity\TypeCentral
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_type_central:
                    referencedColumnName: id_type_central
            orphanRemoval: false
        idDirection:
            targetEntity: SIE\CoreBundle\Entity\DirectionRegionales
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_direction:
                    referencedColumnName: id_direction
            orphanRemoval: false
    manyToMany:
        idEquipementFkEc:
            targetEntity: SIE\CoreBundle\Entity\Equipement
            cascade: {  }
            fetch: LAZY
            mappedBy: idCentralFkEc
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
