SIE\CoreBundle\Entity\ChargeExploitation:
    type: entity
    table: CHARGE_EXPLOITATION
    id:
        idCex:
            id: true
            type: integer
            column: id_cex
            generator:
                strategy: IDENTITY
    fields:
        triCex:
            type: string
            length: 3
            nullable: true
            options:
                fixed: ''
            column: tri_cex
    lifecycleCallbacks: {  }
