SIE\CoreBundle\Entity\CorrespondanceEquipementAdresseMac:
    type: entity
    table: CORRESPONDANCE_EQUIPEMENT_ADRESSE_MAC
    indexes:
        FK_corresp_equip_adress_mac2:
            columns:
                - id_adresse_mac_fk_ceam
        IDX_C6F31288DBFEF7B:
            columns:
                - id_equipement_fk_ceam
    uniqueConstraints:
        id_equipement_fk_ceam:
            columns:
                - id_equipement_fk_ceam
                - id_adresse_mac_fk_ceam
    id:
        idEquipementAdresseMac:
            id: true
            type: integer
            column: id_equipement_adresse_mac
            generator:
                strategy: IDENTITY
    fields:
        infoComp:
            type: string
            length: 25
            nullable: true
            options:
                fixed: ''
            column: info_comp
    manyToOne:
        idAdresseMacFkCeam:
            targetEntity: SIE\CoreBundle\Entity\AdresseMacEquipement
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_adresse_mac_fk_ceam:
                    referencedColumnName: id_adresse_mac_equipement
            orphanRemoval: false
        idEquipementFkCeam:
            targetEntity: SIE\CoreBundle\Entity\Equipement
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_equipement_fk_ceam:
                    referencedColumnName: id_equipement
            orphanRemoval: false
    lifecycleCallbacks: {  }
