SIE\CoreBundle\Entity\Config:
    type: entity
    table: CONFIG
    id:
        idConfig:
            id: true
            type: integer
            column: id_config
            generator:
                strategy: IDENTITY
    fields:
        lienConfig:
            type: string
            length: 90
            nullable: true
            options:
                fixed: ''
            column: lien_config
        libConfig:
            type: string
            length: 75
            nullable: true
            options:
                fixed: ''
            column: lib_config
    lifecycleCallbacks: {  }
