
# src/SIE/CentralBundle/Resources/config/routing.yml
 
 
sie_central_homepage:
    path:     / 
    defaults: { _controller: "SIECentralBundle:Admin:index" }
    methods:  GET



societe:
    path: /getSociete
    defaults: { _controller: "SIECentralBundle:Admin:get_societe" }
    
central_get_all_json:
    path:     /getAll
    defaults: { _controller: "SIECentralBundle:Admin:json_getAll_central" }
   
modif_central:
    path:     /modifCentral
    defaults: { _controller: "SIECentralBundle:Admin:modifCentral" }
    methods:  [POST]
    
select_central:
    path:     /selectCentral/{id}/
    defaults: { _controller: "SIECentralBundle:Admin:selectCentral" }
    
get_all_societe:
    path:     /getAllSociete
    defaults: { _controller: "SIECentralBundle:Admin:get_all_societe" }
 
    


central_get_societe:
    path:     /getSociete
    defaults: { _controller: "SIECentralBundle:ORM:getSociete" }
    methods:  [GET]    
