sie_contrat_homepage:
    path:     /
    defaults: { _controller: "SIEContratBundle:Default:index" }
    
get_contrat:
    path:     /getContrat/{id_contrat}/
    defaults: { _controller: "SIEContratBundle:Admin:getEquipement" }
    
get_contrats:
    path:     /getContrats/{id_central}/
    defaults: { _controller: "SIEContratBundle:Admin:getContratByIdCentral" }

get_all_contrats:
    path:   /getAll
    defaults: { _controller: "SIEContratBundle:Admin:getAll" }


add_contrat:
    path:     /addContrat
    defaults: { _controller: "SIEContratBundle:Admin:addContrat" }
    methods:  [POST]

del_contrat :
    path:     /delContrat
    defaults: { _controller: "SIEContratBundle:Admin:delContrat" }
    methods:  [POST]

update_contrat :
    path:     /updateContrat
    defaults: { _controller: "SIEContratBundle:Admin:updateContrat" }
    methods:  [POST]