get_documents_by_id_central:
    path: /getDocuments/{id_central}
    defaults: { _controller: "SIEDocumentBundle:Admin:getDocuments" }

add_document:
    path:     /add_document
    defaults: { _controller: "SIEDocumentBundle:Admin:add_document" }
    methods:  [POST]